force-app/main/default/objects/NoteSettings__c/NoteSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Note Settings</label>
</CustomObject>

force-app/main/default/objects/NoteSettings__c/fields/NoteLines__c.field-meta.xml
<CustomField>
    <fullName>NoteLines__c</fullName>
    <defaultValue>&#39;&lt;ul&gt;&lt;li&gt;Valid for these countries&lt;/li&gt;&lt;li&gt;Valid for&lt;/li&gt;&lt;li&gt;Valid for&lt;/li&gt;&lt;/ul&gt;&#39;</defaultValue>
    <label>Note Lines</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/NewCreditMemoActionControllerTest.cls
@isTest
private class NewCreditMemoActionControllerTest {

    @testSetup
    private static void setupTestData() {
        String noteLines = '<ul><li>Valid for these countries</li><li>Valid for</li><li>Valid for</li></ul>';
        NoteSettings__c noteSettings = new NoteSettings__c (
            NoteLines__c = noteLines
        );

        insert noteSettings;
    }

    @isTest
    private static void testGetNoteSettings() {
        NoteSettings__c noteSettings = NoteSettings__c.getInstance();
        String preparedNoteLines = noteSettings.NoteLines__c;
        String actualNoteLines;

        Test.startTest();

        actualNoteLines = NewCreditMemoActionController.getNoteSettings();

        Test.stopTest();

        System.assertEquals(preparedNoteLines, actualNoteLines);
    }
}