force-app/main/default/objects/ContentVersion/fields/Expiry_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_From_Date__c</fullName>
    <label>Expiry From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Expiry_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_To_Date__c</fullName>
    <label>Expiry To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/Credit_Memo__c.object-meta.xml
<CustomObject>
    <label>Credit​ ​Memo</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Credit​ ​Memo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit​ ​Memo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Memo__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit​ ​Memo</relationshipLabel>
    <relationshipName>Credit_Memo</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Credit_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Expiry_Date__c</fullName>
    <label>Credit Expiry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Currency_ISO__c.field-meta.xml
<CustomField>
    <fullName>Currency_ISO__c</fullName>
    <label>Currency ISO</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>$</fullName>
                <default>true</default>
                <label>$</label>
            </value>
            <value>
                <fullName>€</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Exclusively_For__c.field-meta.xml
<CustomField>
    <fullName>Exclusively_For__c</fullName>
    <label>​Exclusively​ ​For</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Image_Name__c.field-meta.xml
<CustomField>
    <fullName>Image_Name__c</fullName>
    <label>Image Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Image_Storage__c/Image_Storage__c.object-meta.xml
<CustomObject>
    <label>Image Storage</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Image Storage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Image Storages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Image_Storage__c/fields/Expiry_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_From_Date__c</fullName>
    <label>Expiry From Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Image_Storage__c/fields/Expiry_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_To_Date__c</fullName>
    <label>Expiry To Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Image_Storage__c/fields/Image_Name__c.field-meta.xml
<CustomField>
    <fullName>Image_Name__c</fullName>
    <label>Image Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/VoucherPageController.cls
public with sharing class VoucherPageController {
    public String documentUrl { get; set; }
    public Credit_Memo__c creditMemo { get; set; }
    private static final String URL_DOCUMENT = '/sfc/servlet.shepherd/version/download/';
    private static Credit_Memo__c credit_Memo;

    public VoucherPageController(ApexPages.StandardController controller) {
        VoucherPageController.getCreditMemo();
        creditMemo = credit_Memo;
        documentUrl = VoucherPageController.getDocumentUrl();
    }

    private static void getCreditMemo() {
        VoucherPageController.credit_Memo = [
            SELECT Image_Name__c, Credit_Expiry_Date__c, Exclusively_For__c, Account__r.Name,
                Amount__c, Currency_ISO__c, Name, Note__c
            FROM Credit_Memo__c
            WHERE Id = :ApexPages.currentPage().getParameters().get('id')
        ];
    }

    public static String getDocumentUrl() {
        Id docId;
        String docUrl;
        List<Image_Storage__c> imageSorageList = VoucherPageController.getImageStorage();

        if (!imageSorageList.isEmpty()) {
            docId = VoucherPageController.getDocumentId(imageSorageList[0].Image_Name__c);
        }
        docUrl = URL_DOCUMENT + docId;

        return docUrl;
    }

    private static List<Image_Storage__c> getImageStorage() {
        List<Image_Storage__c> imgSorageList = [
            SELECT Image_Name__c, Expiry_From_Date__c, Expiry_To_Date__c, CreatedDate
            FROM Image_Storage__c
            WHERE Image_Name__c = :credit_Memo.Image_Name__c
                AND Expiry_From_Date__c <= :credit_Memo.Credit_Expiry_Date__c
                AND Expiry_To_Date__c >= :credit_Memo.Credit_Expiry_Date__c
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];

        return imgSorageList;
    }

    private static Id getDocumentId(String imageName) {
        Id documentId;
        Set<String> typeSet = new Set<String> {'jpg', 'jpeg', 'png'};
        List<ContentVersion> documentList = [
            SELECT FileExtension, Title
            FROM ContentVersion
            WHERE FileExtension IN :typeSet
                AND Title = :imageName
            LIMIT 1
        ];

        if (!documentList.isEmpty()) {
            documentId = documentList[0].Id;
        }

        return documentId;
    }
}